### ISSUE TITLE
 Remove commented out code

### ISSUE THREAD

**Issue by dummied** [jajajames/FinalProjectTIY#42]
https://github.com/jajajames/FinalProjectTIY/blob/master/app/models/user.rb#L17
https://github.com/jajajames/FinalProjectTIY/blob/master/app/models/user.rb#L24

**Comment by dummied** [comment]
https://github.com/jajajames/FinalProjectTIY/blob/master/app/views/users/edit.html.erb#L1

**Comment by jameshbush** [comment]
The first ones were for development. Should not be deployed.
